name: J2MC_Core
main: to.joe.j2mc.core.J2MC_Core
version: 1.0
load: STARTUP
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Core.
permissions:
  j2mc.core.admin:
    default: op
    description: is an admin
