name: Core
main: to.joe.j2mc.core.J2MC_Core
version: 1.0
load: STARTUP
loadbefore: [Bans, IRC]
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Core.
commands:
  reloadpermissions:
    description: reload permissions
    permission: j2mc.senior
    permission-message: nope.avi
permissions:
  j2mc.core.admin:
    default: op
    description: is an admin
